export const REQUEST_PLAYER_STATS = 'REQUEST_PLAYER_STATS'
export const ADD_GAME = 'ADD_GAME'
export const RECIEVE_STATS = 'RECIEVE_STATS'
export const RECIEVE_RECENT = 'RECIEVE_RECENT'

export const ADD_TEAM = 'ADD_TEAM'
export const RECIEVE_TEAMS = 'RECIEVE_TEAMS'
export const RECIEVE_ALL_GAMES = 'RECIEVE_ALL_GAMES'

export const SET_COMPARE_A = 'SET_COMPARE_A'
export const SET_COMPARE_B = 'SET_COMPARE_B'
export const CHANGE_FOCUS = 'CHANGE_FOCUS'
